config/routes.rb
Rails.application.routes.draw do
  get "monsters", to: "monsters#index"
  get 'monsters/:id', to: 'monsters#show', as: 'monster'
  devise_for :users
  root to: "home#index"

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = DndWikiSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  def index
    page = params[:page] || 1
    sort_order = params[:sort] || 'asc'
    response = Monsters::ListService.call(page, sort_order)
    @monsters = response[:monsters]
    @pagination = response[:pagination]
  end

  def show
    monster_index = params[:id]
  
    @monster = Monsters::ShowService.call(monster_index)
    if @monster.nil?
      flash[:alert] = "Unable to fetch monster details at this time. Please try again later."
      redirect_to monsters_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/home/index.html.erb
<div class="min-h-screen flex flex-col items-center justify-center bg-[#3b3a30] text-[#faf8ef]">
  <h1 class="text-4xl font-bold mb-10 text-[#b3c100]">Welcome to the D&D Wiki</h1>
  
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 w-full max-w-4xl p-6">
    <%# <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Ability Scores</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Alignments</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Backgrounds</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Classes</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Conditions</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Damage Types</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Equipment</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Equipment Categories</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Feats</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Features</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Languages</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Magic Items</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Magic Schools</h2>
    </div> %>

    <%= link_to monsters_path, class: "block" do %>
      <div class="text-center bg-[#7d5a50] p-6 rounded-lg shadow-lg cursor-pointer hover:shadow-xl transition-shadow">
        <h2 class="text-2xl font-semibold">Monsters</h2>
      </div>
    <% end %>

    <%# <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Proficiencies</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Races</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Rule Sections</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Rules</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Skills</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Spells</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Subclasses</h2>
      <p class="text-[#faf8ef]">Inside Classes</p>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Subraces</h2>
      <p class="text-[#faf8ef]">Inside Races</p>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Traits</h2>
    </div>

    <div class="bg-[#7d5a50] p-6 rounded-lg shadow-lg">
      <h2 class="text-2xl font-semibold">Weapon Properties</h2>
    </div> %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DndWiki</title>
    <%= favicon_link_tag asset_path('dndlogo.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#3b3a30] text-[#faf8ef]">
    <main class="container mx-auto md:mt-28 p-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/monsters/index.html.erb
<div class="flex justify-center mb-4 space-x-4">
  <%= link_to "Sort by Name", monsters_path(sort: @current_sort_order == 'asc' ? 'desc' : 'asc', page: params[:page]), class: 'bg-[#b3c100] text-[#3b3a30] py-2 px-4 rounded-lg font-bold hover:bg-[#a3b100] transition' %>
</div>


<div class="pagination mb-4 text-lg flex justify-center space-x-2">
  <%= paginate @pagination, 
      page_links: true, 
      container: false, 
      class: 'inline-flex rounded-md shadow' %>
</div>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
  <% @monsters.each do |monster| %>
    <div class="bg-[#3b3a30] p-4 rounded-lg shadow-md flex flex-col justify-between">
      <div class="w-full h-48 bg-gray-200 rounded-md mb-4 overflow-hidden">
        <% if monster[:image].present? %>
          <%= image_tag monster[:image], alt: "#{monster[:name]}", class: "w-full h-full object-cover object-top rounded-md" %>
        <% else %>
          <%= image_tag asset_path('dndtemplate.webp'), alt: "No Image Available", class: "w-full h-full object-cover object-top rounded-md" %>
        <% end %>
      </div>

      <div class="flex flex-col flex-grow justify-between">
        <div>
          <h3 class="text-[#faf8ef] text-xl font-bold mb-2"><%= monster[:name] %></h3>
          <p class="text-[#b2b27c] mb-2">Type: <%= monster[:type] %></p>
        </div>
        <%= link_to 'View Details', monster_path(monster[:index]), class: 'bg-[#b3c100] text-[#3b3a30] py-2 px-4 rounded-lg font-bold hover:bg-[#a3b100] transition mt-auto' %>
      </div>
    </div>
  <% end %>
</div>


<div class="pagination mt-8 text-lg flex justify-center space-x-2">
  <%= paginate @pagination, 
      page_links: true, 
      container: false, 
      class: 'inline-flex rounded-md shadow' %>
</div>

app/views/monsters/show.html.erb
<h1 class="text-3xl font-bold mb-4"><%= @monster[:name] %></h1>

<div class="w-full mb-4">
  <%= image_tag @monster[:image], alt: @monster[:name], class: 'w-full h-64 object-cover rounded-lg' %>
</div>

<table class="min-w-full table-auto bg-[#3b3a30] text-[#faf8ef]">
  <tbody>
    <tr>
      <td class="px-4 py-2 border-b">Name</td>
      <td class="px-4 py-2 border-b"><%= @monster[:name] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Description</td>
      <td class="px-4 py-2 border-b"><%= @monster[:desc] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Size</td>
      <td class="px-4 py-2 border-b"><%= @monster[:size] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Type</td>
      <td class="px-4 py-2 border-b"><%= @monster[:type] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Subtype</td>
      <td class="px-4 py-2 border-b"><%= @monster[:subtype] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Alignment</td>
      <td class="px-4 py-2 border-b"><%= @monster[:alignment] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Hit Points</td>
      <td class="px-4 py-2 border-b"><%= @monster[:hit_points] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Armor Class</td>
      <td class="px-4 py-2 border-b">
        <%= @monster[:armor_class] || "No armor class available" %>
      </td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Challenge Rating</td>
      <td class="px-4 py-2 border-b"><%= @monster[:challenge_rating] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Speed (Walk)</td>
      <td class="px-4 py-2 border-b"><%= @monster.dig(:speed, 'walk') %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Proficiencies</td>
      <td class="px-4 py-2 border-b">
        <% if @monster[:proficiencies].any? %>
          <% @monster[:proficiencies].each do |prof| %>
            <div><%= prof['proficiency']['name'] %> (Value: <%= prof['value'] %>)</div>
          <% end %>
        <% else %>
          <div>No proficiencies available</div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Senses</td>
      <td class="px-4 py-2 border-b">Passive Perception: <%= @monster.dig(:senses, 'passive_perception') %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Languages</td>
      <td class="px-4 py-2 border-b"><%= @monster[:languages] %></td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Special Abilities</td>
      <td class="px-4 py-2 border-b">
        <% if @monster[:special_abilities].any? %>
          <% @monster[:special_abilities].each do |ability| %>
            <div><strong><%= ability['name'] %>:</strong> <%= ability['desc'] %></div>
          <% end %>
        <% else %>
          <div>No special abilities available</div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="px-4 py-2 border-b">Actions</td>
      <td class="px-4 py-2 border-b">
        <% if @monster[:actions].any? %>
          <% @monster[:actions].each do |action| %>
            <div><strong><%= action['name'] %>:</strong> <%= action['desc'] %></div>
          <% end %>
        <% else %>
          <div>No actions available</div>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>